spring.application.name=JavaSpringBootBasics
# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/basicspringbootdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=tan10

# Hibernate / JPA properties
spring.jpa.generate.ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.user.name=root
spring.security.user.password=tan10
spring.security.user.roles=ADMIN

#Logging:
logging.level.root=debug

#Profile
spring.profiles.active=dev


#The meaning of the above configuration is that :

# The starting line sets the name of the springboot application, which is helpful while seeing
# the log of the application that this named application is starting.

# spring datasource url means specifies which database to connect , i.e. jdbc:mysql meaning
# jbdc driver will connect to mysql type of db , driver here means that the one which enables
# to connect to database, as driver is the language which allows java to communicate to db .
# then we specify that it is localhost , so that basically means that it is running in our
# local machine, then the port number, here the default port number of mysql is 3306, so that
# So port number basically something that allows to find the service or the appliation to connect
# to in our local system. Think of IP address as localhost , so building number , and port number
# as the room number. As a building will have mul building so will a local system will have
# mul application running at different port number , like tomcat server is running at 8080
# you angular app is running at some different port so which portal to connect to . (IP adress
# is the address of the device connect on the web. So here we are saying that the IP address
# is the localhost. Network or the internet is a channel for communication of devices
# connected to it , which some protocals) . Then we specify our database name , so connect to
# that particular database in the mysql (container for databases) .

# then we will the username and the password to connect to the db. (For password it is recommemded
# not to hardcode it rather use it from .env file .

#spring.jpa.generate.ddl=true that means that it just an instruction for the JPA to allow the
#database creation . This line is not necessary as it used by default by the hibernate

#then we have ddl-auto=update which means that any changes to the db will be migrated by the
#the query , i.e. it keeps the old column with the data, just adds the new column . So the
#old data doesn't get lost , only the new data gets added .It performs the actual create,
#update and delete the db operations.

#show sql is true, which specifies to generate sql queries on the console .