spring.application.name=JavaSpringBootBasics
# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/basicspringbootdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=tan10

# Hibernate / JPA properties
spring.jpa.generate.ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.user.name=root
spring.security.user.password=tan10
spring.security.user.roles=ADMIN
